; Script generated by Antigravity for AutoContent Pro Master Distribution

[Setup]
; --- App Metadata ---
AppId={{C7A9E2B1-4A5B-4E3F-8C7D-9E0A1B2C3D4E}
AppName=AutoContent Pro
AppVersion=1.0.0
AppPublisher=AutoContent Pro Team
AppPublisherURL=https://github.com/imsurajj/autocontent

; --- Paths & Directories ---
DefaultDirName={autopf}\AutoContent Pro
DefaultGroupName=AutoContent Pro
AllowNoIcons=yes

; --- SECURITY: The License Gate ---
UserInfoPage=yes

; --- PRIVACY & SPEED ---
DisableReadyPage=yes

; --- Branding & UI ---
SetupIconFile=image\logo.ico
UninstallDisplayIcon={app}\AutoContentPro.exe
WindowVisible=no
WizardStyle=modern
LicenseFile=LICENSE.rtf
OutputBaseFilename=AutoContent_Pro_Setup
Compression=lzma
SolidCompression=yes

; --- Admin Rights ---
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Messages]
english.UserInfoPageCaption=License Activation
english.UserInfoPageDescription=Enter your unique Activation Key to unlock the installation.

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startupicon"; Description: "Run AutoContent Pro on Windows Startup"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\AutoContent_Ultimate.exe"; DestDir: "{app}"; DestName: "AutoContentPro.exe"; Flags: ignoreversion
Source: "image\logo.png"; DestDir: "{app}\image"; Flags: ignoreversion

[Icons]
Name: "{group}\AutoContent Pro"; Filename: "{app}\AutoContentPro.exe"; IconFilename: "{app}\AutoContentPro.exe"
Name: "{autodesktop}\AutoContent Pro"; Filename: "{app}\AutoContentPro.exe"; Tasks: desktopicon; IconFilename: "{app}\AutoContentPro.exe"
Name: "{userstartup}\AutoContent Pro"; Filename: "{app}\AutoContentPro.exe"; Tasks: startupicon

[Run]
Filename: "{app}\AutoContentPro.exe"; Description: "{cm:LaunchProgram,AutoContent Pro}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Code]
// --- CLEAN INSTALL & VALIDATION ---

procedure CreateLicenseFile;
var
  LicensePath: String;
  DateStr: String;
  FileContent: String;
begin
  LicensePath := ExpandConstant('{userappdata}\AutoContent Pro\license.key');
  // Format current date for the app to read
  DateStr := GetDateTimeString('yyyy-mm-dd', '-', '-');
  DateStr := DateStr + 'T' + GetDateTimeString('hh:nn:ss', ':', ':');
  
  FileContent := '{"date": "' + DateStr + '", "key": "d98d6111195555816560a714cbdd9bda62ff006f7fd4757ba188b3852cbedb27"}';
  
  // Create the directory if it doesn't exist (safety)
  ForceDirectories(ExtractFilePath(LicensePath));
  
  // Write the file
  SaveStringToFile(LicensePath, FileContent, False);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
  begin
    if DirExists(ExpandConstant('{app}')) then
    begin
      DelTree(ExpandConstant('{app}'), True, True, True);
    end;
  end;
  
  // NEW: Create license file AFTER files are copied so app starts activated
  if CurStep = ssPostInstall then
  begin
    CreateLicenseFile;
  end;
end;

procedure InitializeWizard;
begin
  WizardForm.UserInfoNameLabel.Visible := False;
  WizardForm.UserInfoNameEdit.Visible := False;
  WizardForm.UserInfoOrgLabel.Visible := False;
  WizardForm.UserInfoOrgEdit.Visible := False;
  WizardForm.UserInfoSerialLabel.Top := ScaleY(10);
  WizardForm.UserInfoSerialEdit.Top := WizardForm.UserInfoSerialLabel.Top + WizardForm.UserInfoSerialLabel.Height + ScaleY(8);
  WizardForm.UserInfoSerialLabel.Caption := 'Activation Key:';
  WizardForm.UserInfoSerialEdit.PasswordChar := '*';
end;

function CheckSerial(Serial: String): Boolean;
begin
  Result := Trim(Serial) = 'anytime2026';
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = wpUserInfo then
  begin
    if not CheckSerial(WizardForm.UserInfoSerialEdit.Text) then
    begin
      MsgBox('ERROR: Invalid Activation Key. Access Denied.', mbError, MB_OK);
      Result := False;
    end;
  end;
end;
