"""
PDF Batch Generator
-------------------
Reads content from content.md (supports full markdown formatting).
Rephrases only the creative front part of the title via Gemini.
Fixed query from .env is always appended at the end in {{braces}}.

Title output format:
    ✈️ Smart Ways To File An Expedia Dispute Without Stress {{How do I dispute Expedia?}}
    🚨 Easy Steps To Handle An Expedia Dispute Smoothly {{How do I dispute Expedia?}}

Setup:
    pip install -r requirements.txt
    → fill in .env
    → edit content.md
    → python main.py
"""

import os
import re
import sys
from dotenv import load_dotenv
import google.generativeai as genai
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
    ListFlowable, ListItem
)

load_dotenv()

# ── Config from .env ──────────────────────────────────────────────────────────

API_KEY       = os.getenv("GEMINI_API_KEY", "")
MODEL_NAME    = os.getenv("GEMINI_MODEL", "gemini-1.5-flash")
HOW_MANY      = int(os.getenv("HOW_MANY_PDFS", "5"))
PREFIX        = os.getenv("FILE_PREFIX", "exp")
OUTPUT_FOLDER = os.getenv("OUTPUT_FOLDER", "output_pdfs")
QUERY         = os.getenv("TITLE_QUERY", "")     # e.g. How do I dispute Expedia?
TOPIC         = os.getenv("TITLE_TOPIC", "")     # e.g. Expedia dispute guide

if not os.path.isabs(OUTPUT_FOLDER):
    OUTPUT_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), OUTPUT_FOLDER)


# ── Load content.md ───────────────────────────────────────────────────────────

def load_content():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "content.md")
    if not os.path.exists(path):
        print("❌  content.md not found.")
        sys.exit(1)

    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # Drop the first # heading — title is generated by Gemini
    if lines and lines[0].startswith("#"):
        lines = lines[1:]

    return lines


# ── Parse markdown → ReportLab flowables ─────────────────────────────────────

def md_to_story(lines: list, styles) -> list:
    """
    Supported markdown:
      # H1  ## H2  ### H3
      **bold**  *italic*  `code`
      - bullet  (or * or +)
      1. numbered
      > blockquote
      blank line = paragraph break
    """

    h1 = ParagraphStyle("mdH1", parent=styles["Heading1"],
                         fontSize=16, leading=22,
                         textColor=colors.HexColor("#1a1a2e"),
                         spaceBefore=14, spaceAfter=6)

    h2 = ParagraphStyle("mdH2", parent=styles["Heading2"],
                         fontSize=13, leading=18,
                         textColor=colors.HexColor("#2c2c54"),
                         spaceBefore=12, spaceAfter=4)

    h3 = ParagraphStyle("mdH3", parent=styles["Heading3"],
                         fontSize=11, leading=16,
                         textColor=colors.HexColor("#444"),
                         spaceBefore=10, spaceAfter=3)

    body = ParagraphStyle("mdBody", parent=styles["Normal"],
                           fontSize=11, leading=18,
                           textColor=colors.HexColor("#2d2d2d"),
                           spaceAfter=8)

    quote = ParagraphStyle("mdQuote", parent=styles["Normal"],
                            fontSize=11, leading=17,
                            textColor=colors.HexColor("#555555"),
                            leftIndent=20, spaceAfter=8)

    bullet_st = ParagraphStyle("mdBullet", parent=styles["Normal"],
                                fontSize=11, leading=17,
                                textColor=colors.HexColor("#2d2d2d"))

    def inline(text):
        text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
        text = re.sub(r'\*(.+?)\*',     r'<i>\1</i>', text)
        text = re.sub(r'`(.+?)`',       r'<font name="Courier">\1</font>', text)
        return text

    story        = []
    para_lines   = []
    bullet_buf   = []
    num_buf      = []

    def flush_para():
        if para_lines:
            text = " ".join(l.strip() for l in para_lines if l.strip())
            if text:
                story.append(Paragraph(inline(text), body))
            para_lines.clear()

    def flush_bullets():
        if bullet_buf:
            items = [ListItem(Paragraph(inline(b), bullet_st),
                              bulletColor=colors.HexColor("#1a1a2e"))
                     for b in bullet_buf]
            story.append(ListFlowable(items, bulletType='bullet',
                                      leftIndent=20, spaceAfter=8))
            bullet_buf.clear()

    def flush_numbers():
        if num_buf:
            items = [ListItem(Paragraph(inline(n), bullet_st),
                              bulletColor=colors.HexColor("#1a1a2e"))
                     for n in num_buf]
            story.append(ListFlowable(items, bulletType='1',
                                      leftIndent=20, spaceAfter=8))
            num_buf.clear()

    for raw in lines:
        s = raw.rstrip("\n").strip()

        if s.startswith("### "):
            flush_para(); flush_bullets(); flush_numbers()
            story.append(Paragraph(inline(s[4:]), h3))

        elif s.startswith("## "):
            flush_para(); flush_bullets(); flush_numbers()
            story.append(Paragraph(inline(s[3:]), h2))

        elif s.startswith("# "):
            flush_para(); flush_bullets(); flush_numbers()
            story.append(Paragraph(inline(s[2:]), h1))

        elif s.startswith("> "):
            flush_para(); flush_bullets(); flush_numbers()
            story.append(Paragraph(inline(s[2:]), quote))

        elif re.match(r'^[-*+] ', s):
            flush_para(); flush_numbers()
            bullet_buf.append(s[2:])

        elif re.match(r'^\d+\. ', s):
            flush_para(); flush_bullets()
            num_buf.append(re.sub(r'^\d+\. ', '', s))

        elif s == "":
            flush_para(); flush_bullets(); flush_numbers()
            story.append(Spacer(1, 4))

        else:
            flush_bullets(); flush_numbers()
            para_lines.append(s)

    flush_para(); flush_bullets(); flush_numbers()
    return story


# ── Rephrase title prefix via Gemini ─────────────────────────────────────────

used_titles = []

def make_title(attempt: int) -> str:
    """
    Generates:  <emoji> <unique creative phrase> {{QUERY}}
    The QUERY part never changes. Only the prefix is generated by Gemini.
    """
    if not API_KEY or API_KEY == "your_gemini_api_key_here":
        print("❌  Set GEMINI_API_KEY in .env")
        sys.exit(1)

    if not QUERY:
        print("❌  Set TITLE_QUERY in .env  e.g.  TITLE_QUERY=How do I dispute Expedia?")
        sys.exit(1)

    genai.configure(api_key=API_KEY)
    model = genai.GenerativeModel(
        MODEL_NAME,
        generation_config=genai.GenerationConfig(
            temperature=1.8,
            max_output_tokens=80,
        )
    )

    already = "\n".join(f"- {t}" for t in used_titles) if used_titles else "None"
    topic_hint = f"Topic: {TOPIC}\n" if TOPIC else ""

    prompt = (
        f"You write catchy article title prefixes.\n\n"
        f"{topic_hint}"
        f"Fixed query (always appended at the end, DO NOT include it): {QUERY}\n\n"
        f"Write ONLY a short punchy prefix (5–9 words) that naturally leads into that query.\n"
        f"Always start with a relevant emoji. Vary the style each time:\n"
        f"  Action  → 'Smart Ways To File An Expedia Dispute Without Stress'\n"
        f"  How-to  → 'How To Resolve An Expedia Dispute Like a Pro'\n"
        f"  Benefit → 'Stress-Free Tips For Winning Your Expedia Dispute'\n"
        f"  Urgent  → 'Quick Fix: Handle Your Expedia Dispute Today'\n"
        f"  Bold    → 'Hassle-Free Guide To Filing An Expedia Dispute Fast'\n\n"
        f"Already used (DO NOT repeat or closely copy):\n{already}\n\n"
        f"Variation #{attempt} — return ONLY the emoji + prefix phrase, nothing else:"
    )

    response = model.generate_content(prompt)
    prefix = response.text.strip().strip('"').strip("'")
    used_titles.append(prefix)

    # Final title:  ✈️ Smart Ways To ... {{How do I dispute Expedia?}}
    return f"{prefix} {{{{{QUERY}}}}}"


# ── Build one PDF ─────────────────────────────────────────────────────────────

def build_pdf(filepath: str, title: str, md_lines: list):
    doc = SimpleDocTemplate(
        filepath, pagesize=A4,
        leftMargin=2.5*cm, rightMargin=2.5*cm,
        topMargin=2.5*cm, bottomMargin=2.5*cm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("MainTitle", parent=styles["Title"],
                                  fontSize=17, leading=24,
                                  textColor=colors.HexColor("#1a1a2e"),
                                  spaceAfter=6)

    story = []
    story.append(Paragraph(title, title_style))
    story.append(Spacer(1, 0.2*cm))
    story.append(HRFlowable(width="100%", thickness=1.5,
                             color=colors.HexColor("#1a1a2e"), spaceAfter=10))
    story.extend(md_to_story(md_lines, styles))
    doc.build(story)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    md_lines = load_content()
    os.makedirs(OUTPUT_FOLDER, exist_ok=True)

    print(f"\n  Query      : {QUERY}")
    print(f"  Generating : {HOW_MANY} PDFs  →  {OUTPUT_FOLDER}\n")

    for i in range(1, HOW_MANY + 1):
        filename = f"{PREFIX}{i:02d}.pdf"
        filepath = os.path.join(OUTPUT_FOLDER, filename)

        print(f"[{i}/{HOW_MANY}] Generating title...", end=" ", flush=True)
        try:
            title = make_title(attempt=i)
            print("✓")
        except Exception as e:
            print(f"⚠ Gemini error ({e}), using fallback.")
            title = f"Guide #{i} {{{{{QUERY}}}}}"

        print(f"        → {title}")
        build_pdf(filepath, title, md_lines)
        print(f"        Saved: {filename}\n")

    print(f"✅  Done! {HOW_MANY} PDFs saved to:\n   {OUTPUT_FOLDER}\n")


if __name__ == "__main__":
    main()